// Mock Data
export const mockData = {
    villages: {
        Bhoewali: { screened: 150, highRisk: 20 },
        Kotli: { screened: 120, highRisk: 15 },
        "Nawan Pind": { screened: 112, highRisk: 18 },
        Sangatpura: { screened: 100, highRisk: 10 },
    },
    patients: [
        {
            id: 1,
            name: "Sunita Devi",
            age: 28,
            pregnancy: "5 Months",
            risk: 8.2,
            status: "Referred",
            village: "Bhoewali",
            referredOn: "2025-09-05",
            referralStatus: "Completed",
        },
        {
            id: 2,
            name: "Geeta Rani",
            age: 31,
            pregnancy: "7 Months",
            risk: 9.1,
            status: "High Risk",
            village: "Bhoewali",
            referredOn: "2025-09-08",
            referralStatus: "Pending",
        },
        {
            id: 3,
            name: "Manpreet Kaur",
            age: 25,
            pregnancy: "4 Months",
            risk: 4.5,
            status: "Normal",
            village: "Kotli",
        },
        {
            id: 4,
            name: "Priya Sharma",
            age: 29,
            pregnancy: "6 Months",
            risk: 8.5,
            status: "High Risk",
            village: "Nawan Pind",
            referredOn: "2025-09-07",
            referralStatus: "Reviewed",
        },
        {
            id: 5,
            name: "Ritu Kumari",
            age: 22,
            pregnancy: "3 Months",
            risk: 6.1,
            status: "Mild",
            village: "Sangatpura",
        },
        {
            id: 6,
            name: "Kamlesh",
            age: 34,
            pregnancy: "8 Months",
            risk: 9.5,
            status: "Referred",
            village: "Kotli",
            referredOn: "2025-09-01",
            referralStatus: "Completed",
        },
    ],
    referralTimeline: [
        {
            status: "Marked as High Risk",
            date: "2025-09-08",
            user: "ASHA Worker",
            note: "Patient reported dizziness.",
        },
        {
            status: "Referred to PHC",
            date: "2025-09-08",
            user: "System",
            note: "Automatically referred by Asha AI-Screen.",
        },
        {
            status: "Appointment Scheduled",
            date: "2025-09-09",
            user: "Dr. Sharma",
            note: "Scheduled for tomorrow at 11 AM.",
        },
    ],
};
